apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: q8rkb1w27-go 
  janus-idp.io/tekton: q8rkb1w27-go
  backstage.io/kubernetes-id: q8rkb1w27-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: q8rkb1w27-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml