apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: q8rkb1w27-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: q8rkb1w27-go 
  name: q8rkb1w27-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: q8rkb1w27-go 
